### ISSUE TITLE
Using this addon leads to duplicate styled-components

### ISSUE THREAD

**Issue by AlexBrohshtut** [atlassian-labs/storybook-addon-performance#101]
styled-components [is defined ](https://github.com/atlassian-labs/storybook-addon-performance/blob/e9c8e93e91f8bb489eb63a80dedc27a314610027/packages/storybook-addon-performance/package.json#L38) as a direct dependency, which leads to multiple styled-components being installed in node-modules and to issues within the application. [Here](https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library) is the explanation for the library authors on what to do in that case. 

Can you please look into this and possible move the styled-components to the peer dependencies instead? 

Thanks.

**Comment by DarkPurple141** [comment]
I think this has been resolved - let me know if it's still a problem.
