### ISSUE TITLE
Latest published version (0.17.0) not on npm

### ISSUE THREAD

**Issue by Niznikr** [atlassian-labs/storybook-addon-performance#130]
It seems there [might have been an error](https://github.com/atlassian-labs/storybook-addon-performance/actions/runs/4110538980/jobs/7093461341) in publishing `0.17.0` on npm? Can't seem to find it there.

**Comment by jgodi** [comment]
Ya, I was seeing the same thing. It looks like an[ auth issue](https://github.com/atlassian-labs/storybook-addon-performance/actions/runs/4110538980/jobs/7093461341#step:7:498) for publishing. 

Once this is published, I can use it in my project using SB v7 to test everything out too. Very excited!

**Comment by DarkPurple141** [comment]
Yep looking at this now thanks folks, need to update the old token.

**Comment by DarkPurple141** [comment]
Looks like we're now published with `v0.17.0`! Thanks for your patience!
