### ISSUE TITLE
Addon is calling examples instead of treating them as components

### ISSUE THREAD

**Issue by madou** [atlassian-labs/storybook-addon-performance#2]
If I have an example with hooks in it things blow up. This is because you're calling them instead of wrapping them in a `React.createElement` (or just rendering the JSX).

This can be fixed or at least documented depending on the implications of running the perf checks.

---

```
git clone git@github.com:atlassian-labs/compiled-css-in-js.git
cd compiled-css-in-js
yarn
yarn start
```

then smash the start all button

**Comment by alexreardon** [comment]
Wrong repo? ^ @madou

**Comment by madou** [comment]
Nope @alexreardon

**Comment by alexreardon** [comment]
Oh!

**Comment by alexreardon** [comment]
I'll take a look

**Comment by madou** [comment]
![image](https://user-images.githubusercontent.com/6801309/78727156-3e35be00-7977-11ea-8925-b87ba2831d5f.png)

**Comment by alexreardon** [comment]
I think we might be running into issue #1 (I hope not though)

**Comment by alexreardon** [comment]
```
storybook-addon-performance@^0.4.0:
  version "0.4.0"
  resolved "https://registry.yarnpkg.com/storybook-addon-performance/-/storybook-addon-performance-0.4.0.tgz#cf732c2e537c248893bd5a952a08d37dfb090003"
  integrity sha512-GkH7iA59D3nctO3bnzQBLAIxUMeYLYuDrfvwrVGfPzcK6+chU1vYvvbwQoiXV/tMGvTbE0nQX2Qnv39QIRYKbg==
  dependencies:
    "@storybook/addons" "^5.3.18"
    "@storybook/api" "^5.3.18"
    "@storybook/components" "^5.3.18"
    "@storybook/core-events" "^5.3.18"
    "@storybook/theming" "^5.3.18"
    "@xstate/react" "1.0.0-rc.3"
    gzip-js "^0.3.2"
    tiny-invariant "^1.1.0"
    xstate "^4.8.0"
```

**Comment by alexreardon** [comment]
Right now the addon is (incorrectly) not even stating a dependency on react or react dom

**Comment by alexreardon** [comment]
(it should be a peer dep)

**Comment by alexreardon** [comment]
I have created an example in a different storybook that is using a hook and I am not running into this error 🤔
