### ISSUE TITLE
Feature request: use production bundles for perf testing.

### ISSUE THREAD

**Issue by dzearing** [atlassian-labs/storybook-addon-performance#28]
I'm not deeply familiar with where the bundling happens (I think it's storybook) but it would be ideal to do performance measurements using production bundles where `process.env.NODE_ENV === 'production'`. This would ensure that the perf numbers are running on production React which has quite different characteristics than development.

Is there any way for the addon to create a prod bundle to run against? I am really unsure if this is possible without requiring the author to setup a custom storybook webpack bundle config, but thought I'd bring it up as I've certainly seen huge difference in numbers with that on where things can run in optimized mode.

**Comment by alexreardon** [comment]
If you build your storybook in production mode you should be getting near production numbers

**Comment by alexreardon** [comment]
The numbers will be a touch slower as the code is running in an iframe which generally seems to perform a bit slower
