### ISSUE TITLE
import / export pins

### ISSUE THREAD

**Issue by alexreardon** [atlassian-labs/storybook-addon-performance#30]
It would be great to be able to export pinned values, and then later import them. This would allow for long term saving as well as sharing. 

Currently, we cannot do this with the URL because of an issue with storybook: https://github.com/storybookjs/storybook/issues/8600

We might have to use the file API for now

**Comment by DarkPurple141** [comment]
Some offhand notes in the process of working on this:

Should uploading auto-pin (probably?)
Should downloading download what is pinned or the current result (probably the current result?)
Other?
