### ISSUE TITLE
Unexpected token export being thrown when running storyshots through jest

### ISSUE THREAD

**Issue by sumboxcar182** [atlassian-labs/storybook-addon-performance#36]
Hello!

We are looking to bring this addon into our storybook, as it's already paying off when we're testing stuff out. However when running storyshots, jest is throwing an error of unexpected token export when trying to run storyshots.

Inspecting the error it looks like this is due to the package having the export in index.js which throws the error in jest as i think by default babel does not polyfill node modules.

Below is the error we're hitting and note i cut the path to just the node modules so you're not seeing my horrible directory lol.

```
C:\node_modules\storybook-addon-performance\dist\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as withPerformance } from './decorator/decorator';
 ^^^^^^

SyntaxError: Unexpected token export
```

Is there anything i can do to help with this? I figure i tell babel to transform this package, but wasn't sure if the library itself can be shipped as es5 to work with jest out of the box.

**Comment by marboro92** [comment]
@sumboxcar182 I had the same issue, as you said, I ended up having to change my jest settings under `transformIgnorePatterns` to tranform this particular node_module

```
 "jest": {
    "transform": {
      "^.+\\.jsx?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!storybook-addon-performance)"
    ],
  }
```

**Comment by sumboxcar182** [comment]
Ah thank you! I'll take a look at that and hopefully that solves the issue

**Comment by ekros** [comment]
Same issue here. Unfortunately, the @marboro92 did not work in my case. I'm using Jest 24 and the option seems to exist so I coulnd't guess the problem. That's a pity because the addon is pretty useful!

**Comment by DarkPurple141** [comment]
Hey folks we do support CJS support so this should be resolved. Feel free to re-open this if you're still experiencing the issue.
