### ISSUE TITLE
Storybook story source shows <TaskHarness ... /> instead of actual code

### ISSUE THREAD

**Issue by mploetz** [atlassian-labs/storybook-addon-performance#37]
## Summary

The `Story source` does not show correct source code of the component with this addon. Instead all stories show with:
```
<TaskHarness
    channel={[object Object]}
    getNode={function noRefCheck() {}}
    interactions={undefined}
/>
```

Currently I add the this addon in the config with `addDecorator(withPerformance)` as recommended. Is there something that I am missing in terms of implementation whether it be with the stories or how I add this addon?

**Comment by mploetz** [comment]
Looks like it was actually a problem with the order of parsing the components source rather than the addition.

**Comment by tadjohnston** [comment]
Can I ask how you fixed this? I'm having the same issue.

**Comment by seanmaisch** [comment]
> Looks like it was actually a problem with the order of parsing the components source rather than the addition.

I'm still experiencing this issue 2 years later and can't seem to find a fix. Do you or @tadjohnston have a suggestion, please?

**Comment by tadjohnston** [comment]
@seanmaisch I haven't had an issue since additional releases of Storybook and other various package updates.  Wish I could help more.
