### ISSUE TITLE
Remove types option in TSConfig once Cypress fix their global types issue

### ISSUE THREAD

**Issue by danieldelcore** [atlassian-labs/storybook-addon-performance#38]
https://github.com/atlassian-labs/storybook-addon-performance/blob/e1ea11f7c234b2d0456c87450fdccfb9c2076f64/tsconfig.json#L15

Issue thread: https://github.com/cypress-io/cypress/issues/6690
PR open on Cypress: https://github.com/cypress-io/cypress/pull/7194

**Comment by davilima6** [comment]
@danieldelcore, @justman00: may this one be closed?

**Comment by danieldelcore** [comment]
Yep! Wonderful!! Thanks for letting us know @davilima6 !
