### ISSUE TITLE
Needs transpiling downstream with latest Storybook 6

### ISSUE THREAD

**Issue by m7kvqbe1** [atlassian-labs/storybook-addon-performance#53]
It looks like we have to transpile this downstream in order to get it to play nice with IE/Edge.

Does it make sense to publish a transpiled build of the package so that consumers don't need to manually tweak their storybook config to do so?

If someone has managed to transpile this addon downstream as part of their storybook build it would be greatly appreciated if you could share some config with us - we are struggling to get this to work.

**Comment by davilima6** [comment]
I'm afraid this has to reopened. The files in the new `cjs/` are still in ES6, e.g. using arrow functions and template strings.

**Comment by DarkPurple141** [comment]
Yep, no worries, I think I confused this with the other request for CJS support in general.
