### ISSUE TITLE
Usage recommendation: dev server vs static build

### ISSUE THREAD

**Issue by sheelah** [atlassian-labs/storybook-addon-performance#94]
Thanks for creating this awesome add-on! 🙌🏻 

Question on recommended usage: is this designed to be run only off a static Storybook build, so that the production version of React is used? The React docs recommend doing perf benchmarking when using the minified prod build (not the dev server) so I'm wondering if that applies here too.  Thanks for any insight.

**Comment by DarkPurple141** [comment]
Yes it's recommended to use a production build, although it does work with a dev build. You'll see less variability with production.

**Comment by sheelah** [comment]
Thank you @DarkPurple141! If the team would like, I'm happy to submit a PR adding a note about this to the documentation.

**Comment by DarkPurple141** [comment]
That would be great, please submit one and I'll triage it through.

**Comment by sheelah** [comment]
PR for this: https://github.com/atlassian-labs/storybook-addon-performance/pull/98
