### ISSUE TITLE
Does this addon work with Storybook 6.4?

### ISSUE THREAD

**Issue by bebraw** [atlassian-labs/storybook-addon-performance#96]
Has anyone tried the addon with Storybook 6.4? Is there anything specific to consider in this use case?

**Comment by DarkPurple141** [comment]
Are you having issues with `v6.4` can you provide any additional information / a minimal repo?

**Comment by bebraw** [comment]
Thanks for getting back to me. The UI shows up but that's about it. I will try to simplify this into something I can share after the holidays as it's from a client project.

**Comment by mstelz** [comment]
I have it working fine with the latest version of 6.4

**Comment by manavkodnanimeesho** [comment]
@mstelz @DarkPurple141 @mstelz For me also the performance tab shown on all stories but clicking on start all just disables that button and no results are shown, any work around for what you did ?
